package:
  name: polymetis
  version: {{ GIT_BUILD_STR }}

source:
  git_url: ../../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  run_exports:
    - {{ pin_subpackage('polymetis', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - cudatoolkit=11.3
    - doxygen
    - eigen=3.3.9
    - grpc-cpp
    - libprotobuf
    - openmpi
    - pinocchio ==2.5.2
    - poco ==1.9.0 # needed by libfranka
    - python
    - pytorch ==1.10.0
    - urdfdom
    - urdfdom_headers
    - yaml-cpp

  run:
    - black
    - boost ==1.72.0
    - boost-cpp ==1.72.0
    - breathe
    - cpuonly
    - dash
    - doxygen
    - grpc-cpp
    - grpcio
    - habitat-sim=0.2.1=py3.8_bullet_linux_fc7fb11ccec407753a73ab810d1dbb5f57d0f9b9
    - hydra-core==1.0.6
    - myst-parser
    - numpy
    - openmpi
    - pandas
    - pinocchio ==2.5.2
    - plotly
    - poco ==1.9.0 # needed by libfranka
    - protobuf
    - pybullet ==3.17
    - pytest
    - pytest-benchmark
    - python
    - pytorch ==1.10.0
    - scipy
    - sphinx
    - sphinx-book-theme
    - tqdm
    - withbullet

about:
  home:
