ip: localhost
hz: 240
gui: true
use_grav_comp: false
use_real_time: false

robot_client:
  _target_: polysim.grpc_sim_client.GrpcSimulationClient
  env_cfg:
    _target_: polysim.envs.BulletRobotEnv
    gui: ${gui}
    use_grav_comp: ${use_grav_comp}
    robot_model_cfg: ${robot_model}
  metadata_cfg:
    _target_: polymetis.robot_client.metadata.RobotClientMetadata
    default_Kq: [ 30, 60, 30, 30, 60, 30, 30,30, 60, 30, 30, 30, 60, 30, 30, 30 ]
    default_Kqd: [ .1, .1, .06, .06, .06, .06, .06, .06, .06, .06, .06, .06, .06, .06, .06, .06 ]
    default_Kx: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
    default_Kxd: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
    hz: ${hz}
    robot_model_cfg: ${robot_model}
  ip: ${ip}
  port: ${port}
