ip: localhost
hz: 240
gui: true
use_grav_comp: true
use_real_time: false

default_Kq: [100., 150., 50., 75., 25., 10., 10.]
default_Kqd: [10., 20., 5., 10., 2.5, 1., 0.5]
default_Kx: [100, 100, 100, 40, 40, 40]
default_Kxd: [1, 1, 1, 0.2, 0.2, 0.2]

robot_client:
  _target_: polysim.grpc_sim_client.GrpcSimulationClient
  env_cfg:
    _target_: polysim.envs.BulletManipulatorEnv
    gui: ${gui}
    use_grav_comp: ${use_grav_comp}
    robot_model_cfg: ${robot_model}
  metadata_cfg:
    _target_: polymetis.robot_client.metadata.RobotClientMetadata
    default_Kq: ${default_Kq}
    default_Kqd: ${default_Kqd}
    default_Kx: ${default_Kx}
    default_Kxd: ${default_Kxd}
    hz: ${hz}
    robot_model_cfg: ${robot_model}
  ip: ${ip}
  port: ${port}
