fixes:
  - "/shared/droidlet::"
  - "/droidlet::"

coverage:
  status:
    project:
        default:
            target: 0%
        Robot:
            target: 0%
            paths:
                - agents/locobot/*
        Minecraft:
            target: 0%
            paths:
                - agents/minecraft/*
        Droidlet:
            target: 0%
            paths:
                - droidlet/*
    patch: off
    changes: off

comment: false

