ignore:
      - "**/tests/*.py"
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project:
        default:
            target: 0%
            if_not_found: success
            if_ci_failed: success
        Robot:
            target: 0%
            paths:
                - agents/locobot/*
            if_not_found: success
            if_ci_failed: success
                
        Mincraft:
            target: 0%
            paths:
                - agents/minecraft/*
            if_not_found: success
            if_ci_failed: success
	    
        Droidlet:
            target: 0%
            paths:
                - droidlet/*
            if_not_found: success
            if_ci_failed: success

    patch: off
    changes: off

comment: false

