fixes:
  - "/shared/droidlet::"
  - "/droidlet::"
  - "/shared/fairo::"
  - "/fairo::"

coverage:
  status:
    project:
        default:
            target: 0%
        Robot:
            target: 0%
            paths:
                - agents/locobot/*
        Minecraft:
            target: 0%
            paths:
                - agents/minecraft/*
        Droidlet:
            target: 0%
            paths:
                - droidlet/*
    patch: off
    changes: off

comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes 