fixed_span_values = {
    "ABSOLUTE": 0,
    "AGENT": 1,
    "BUILD": 2,
    "CURRENTLY_RUNNING": 3,
    "DANCE": 4,
    "DEFAULT": 5,
    "DESTROY": 6,
    "DIG": 7,
    "FILL": 8,
    "FINISHED": 9,
    "FIRST": 10,
    "FREEBUILD": 11,
    "GET": 12,
    "MOVE": 13,
    "RESUME": 14,
    "SELF": 15,
    "SCOUT": 16,
    "STOP": 17,
    "SPAWN": 18,
    "SPEAKER": 19,
    "SPEAKER_LOOK": 20,
    "UNDO": 21,
    "-360": 22,
    "-180": 23,
    "-135": 24,
    "-90": 25,
    "-45": 26,
    "45": 27,
    "90": 28,
    "135": 29,
    "180": 30,
    "360": 31,
    "0": 32,
    "BLOCK": 33,
    "THIS": 34,
    "SECOND": 35,
}
fixed_span_values_voc = {v: k for k, v in fixed_span_values.items()}

tree_keys_capital = [
    "has_tag",
    "block_type",
    "REWARD",
    "PUT_MEMORY",
    "FIRST",
    "TAG",
    "BORN_TIME",
    "DIG",
    "LEFT",
    "where_clause",
    "135",
    "special_reference",
    "ANY",
    "Other",
    "obj_text",
    "dialogue_type",
    "attribute",
    "BLOCK_TYPE",
    "DESTROY",
    "AROUND",
    "has_thickness",
    "BETWEEN",
    "reference_object_1",
    "has_block_type",
    "-45",
    "ADJACENT_TO_BLOCK_TYPE",
    "COMPOSITE_ACTION",
    "fixed_value",
    "action_type",
    "has_width",
    "pred_text",
    "look_turn",
    "condition_type",
    "NAME",
    "TASKS",
    "MIN",
    "HUMAN_GIVE_COMMAND",
    "event_sequence",
    "point",
    "argval",
    "BOT_CAPABILITIES",
    "DISALLOWED",
    "memory_type",
    "CURRENTLY_RUNNING",
    "has_name",
    "AWAY",
    "SPEAKER_LOOK",
    "has_measure",
    "SPAWN",
    "CURRENT_TIME",
    "comparison_type",
    "BUILD",
    "RUN_COUNT",
    "reward_value",
    "input_right",
    "MAX",
    "COMPARATOR",
    "relative_yaw",
    "SCOUT",
    "reference_object_2",
    "ALL",
    "text_span",
    "180",
    "return_quantity",
    "has_length",
    "special",
    "LOCATION",
    "has_size",
    "RIGHT",
    "NEVER",
    "GET_MEMORY",
    "AND",
    "SECOND",
    "same",
    "0",
    "OUTSIDE",
    "selector",
    "ordinal",
    "SELF",
    "-90",
    "STOP",
    "MEMORY",
    "dance_type",
    "reference_object",
    "location_type",
    "has_depth",
    "THIS",
    "steps",
    "UP",
    "schematic",
    "SPEAKER",
    "input_left",
    "OTHER",
    "HEIGHT",
    "memory_data",
    "receiver",
    "source",
    "FRONT",
    "contains_coreference",
    "polarity",
    "angle",
    "360",
    "TRIPLE",
    "yes",
    "FREEBUILD",
    "terminate_condition",
    "relative_direction",
    "AGENT",
    "coordinates_span",
    "DANCE",
    "OTHERACTION",
    "RESUME",
    "has_height",
    "filters",
    "body_turn",
    "location",
    "condition",
    "UNDO",
    "-360",
    "BACK",
    "RANDOM",
    "EQUAL",
    "NEAR",
    "MOVE",
    "NEGATIVE",
    "NOOP",
    "DOWN",
    "COLOUR",
    "quantity",
    "-135",
    "linear_extent",
    "condition_span",
    "relative_pitch",
    "has_colour",
    "90",
    "45",
    "GET_CAPABILITIES",
    "target_action_type",
    "POSITIVE",
    "yaw",
    "output",
    "upsert",
    "GET",
    "ALLOWED",
    "triples",
    "INSIDE",
    "REFERENCE_OBJECT",
    "FILL",
    "dialogue_target",
]
TREE_KEYs = [x.lower() for x in tree_keys_capital]
