# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Droidlet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Droidlet
  pod 'ARCore/CloudAnchors'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod "SimpleKeychain"
  pod 'SwiftJWT'
  pod 'GLTFSceneKit'
  pod 'SDWebImageSwiftUI'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  
end
