# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polygrasp/polygrasp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19polygrasp/polygrasp.proto\x12\tpolygrasp\"\x15\n\x05Image\x12\x0c\n\x04rgbd\x18\x01 \x01(\x0c\"&\n\nObjectMask\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04mask\x18\x02 \x01(\x0c\"(\n\nPointCloud\x12\x0b\n\x03pcd\x18\x01 \x01(\x0c\x12\r\n\x05\x63olor\x18\x02 \x01(\x0c\"\'\n\nGraspGroup\x12\x19\n\x11grasp_group_array\x18\x01 \x01(\x0c\x32N\n\x0bGraspServer\x12?\n\tGetGrasps\x12\x15.polygrasp.PointCloud\x1a\x15.polygrasp.GraspGroup\"\x00(\x01\x30\x01\x32\x9b\x01\n\x10PointCloudServer\x12>\n\rGetPointcloud\x12\x10.polygrasp.Image\x1a\x15.polygrasp.PointCloud\"\x00(\x01\x30\x01\x12G\n\x11SegmentPointcloud\x12\x15.polygrasp.PointCloud\x1a\x15.polygrasp.ObjectMask\"\x00(\x01\x30\x01\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_OBJECTMASK = DESCRIPTOR.message_types_by_name['ObjectMask']
_POINTCLOUD = DESCRIPTOR.message_types_by_name['PointCloud']
_GRASPGROUP = DESCRIPTOR.message_types_by_name['GraspGroup']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'polygrasp.polygrasp_pb2'
  # @@protoc_insertion_point(class_scope:polygrasp.Image)
  })
_sym_db.RegisterMessage(Image)

ObjectMask = _reflection.GeneratedProtocolMessageType('ObjectMask', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTMASK,
  '__module__' : 'polygrasp.polygrasp_pb2'
  # @@protoc_insertion_point(class_scope:polygrasp.ObjectMask)
  })
_sym_db.RegisterMessage(ObjectMask)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUD,
  '__module__' : 'polygrasp.polygrasp_pb2'
  # @@protoc_insertion_point(class_scope:polygrasp.PointCloud)
  })
_sym_db.RegisterMessage(PointCloud)

GraspGroup = _reflection.GeneratedProtocolMessageType('GraspGroup', (_message.Message,), {
  'DESCRIPTOR' : _GRASPGROUP,
  '__module__' : 'polygrasp.polygrasp_pb2'
  # @@protoc_insertion_point(class_scope:polygrasp.GraspGroup)
  })
_sym_db.RegisterMessage(GraspGroup)

_GRASPSERVER = DESCRIPTOR.services_by_name['GraspServer']
_POINTCLOUDSERVER = DESCRIPTOR.services_by_name['PointCloudServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=40
  _IMAGE._serialized_end=61
  _OBJECTMASK._serialized_start=63
  _OBJECTMASK._serialized_end=101
  _POINTCLOUD._serialized_start=103
  _POINTCLOUD._serialized_end=143
  _GRASPGROUP._serialized_start=145
  _GRASPGROUP._serialized_end=184
  _GRASPSERVER._serialized_start=186
  _GRASPSERVER._serialized_end=264
  _POINTCLOUDSERVER._serialized_start=267
  _POINTCLOUDSERVER._serialized_end=422
# @@protoc_insertion_point(module_scope)
