name: pyrbgt
channels:
  - conda-forge
  - pytorch3d
  - plotly
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit
  - eigen
  - glew
  - glfw
  - matplotlib
  - opencv
  - plotly
  - python=3.8
  - pytorch3d
  - pytorch::pytorch
  - scipy
