robot:
  _target_: polygrasp.robot_interface.GraspingRobotInterface
  ip_address: "172.16.0.1"
  k_approach: 0.9
  k_grasp: 0.55
  gripper_max_width: 0.085
  enforce_version: false
  gripper:
    _target_: polymetis.GripperInterface
    ip_address: "172.16.0.1"
